        !COMPILER-GENERATED INTERFACE MODULE: Thu Mar 14 17:32:06 2024
        MODULE READ2PCUBICNC__genmod
          INTERFACE 
            SUBROUTINE READ2PCUBICNC(NC,NIN,NOUT)
              INTEGER(KIND=4) :: NC
              INTEGER(KIND=4) :: NIN
              INTEGER(KIND=4) :: NOUT
            END SUBROUTINE READ2PCUBICNC
          END INTERFACE 
        END MODULE READ2PCUBICNC__genmod
